services:
  db-mysql:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD

    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db-mysql:
        condition: service_healthy
    restart: on-failure
    image: accommodation-booking-app
    build: .
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db-mysql:3306/accommodation_booking_db",
        "spring.datasource.username":"${MYSQLDB_USER}",
        "spring.datasource.password":"${MYSQLDB_PASSWORD}",
        "jwt.expiration":"${JWT_EXPIRATION}",
        "jwt.secret":"${JWT_SECRET}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
    ports:
      - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
      - "$DEBUG_PORT:$DEBUG_PORT"
